name: pardikte
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
 # Enkripsi AES
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  provider: ^6.1.4
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.3.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.3.0
  file_picker: ^10.1.2
  uuid: ^4.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
